-- DELETE from lesson WHERE lesson_id>=500; 
INSERT INTO lesson ( lesson_id, status_id, vehicle_id, type_id, url_private, description, name, code) VALUES(501, 1, 1, 1, '', '','Anti-Lock Brakes','ABS');
INSERT INTO lesson ( lesson_id, status_id, vehicle_id, type_id, url_private, description, name, code) VALUES(502, 1, 1, 1, '', '','Aggressive Driving','AGD');
INSERT INTO lesson ( lesson_id, status_id, vehicle_id, type_id, url_private, description, name, code) VALUES(503, 1, 1, 1, '', '','Anticipating the Other Motorist','AOM');
INSERT INTO lesson ( lesson_id, status_id, vehicle_id, type_id, url_private, description, name, code) VALUES(504, 1, 1, 1, '', '','The Fuel-Efficient Eco Attitude','ATD');
INSERT INTO lesson ( lesson_id, status_id, vehicle_id, type_id, url_private, description, name, code) VALUES(505, 1, 1, 1, '', '','Auto Theft and Theft From Auto','ATH');
INSERT INTO lesson ( lesson_id, status_id, vehicle_id, type_id, url_private, description, name, code) VALUES(506, 1, 1, 1, '', '','Challenging Weather Conditions','CHW');
INSERT INTO lesson ( lesson_id, status_id, vehicle_id, type_id, url_private, description, name, code) VALUES(507, 1, 1, 1, '', '','Safe Driving in Construction Zones ','CTZ');
INSERT INTO lesson ( lesson_id, status_id, vehicle_id, type_id, url_private, description, name, code) VALUES(508, 1, 1, 1, '', '','Defensive Backing Strategies ','DBS');
INSERT INTO lesson ( lesson_id, status_id, vehicle_id, type_id, url_private, description, name, code) VALUES(509, 1, 1, 1, '', '','Defensive Driving','DEF');
INSERT INTO lesson ( lesson_id, status_id, vehicle_id, type_id, url_private, description, name, code) VALUES(510, 1, 1, 1, '', '','Avoiding Deer and Debris Collisions','DER');
INSERT INTO lesson ( lesson_id, status_id, vehicle_id, type_id, url_private, description, name, code) VALUES(511, 1, 1, 1, '', '','Danger Zones','DNZ');
INSERT INTO lesson ( lesson_id, status_id, vehicle_id, type_id, url_private, description, name, code) VALUES(512, 1, 1, 1, '', '','Defensive Parking Strategies','DPS');
INSERT INTO lesson ( lesson_id, status_id, vehicle_id, type_id, url_private, description, name, code) VALUES(513, 1, 1, 1, '', '','Alcohol, Drugs and Driving ','DUI');
INSERT INTO lesson ( lesson_id, status_id, vehicle_id, type_id, url_private, description, name, code) VALUES(514, 1, 1, 1, '', '','Managing Emissions on the Road','EMI');
INSERT INTO lesson ( lesson_id, status_id, vehicle_id, type_id, url_private, description, name, code) VALUES(515, 1, 1, 1, '', '','Avoiding Collisions With Fixed Objects','FXD');
INSERT INTO lesson ( lesson_id, status_id, vehicle_id, type_id, url_private, description, name, code) VALUES(516, 1, 1, 1, '', '','Fuel Consumption','GAS');
INSERT INTO lesson ( lesson_id, status_id, vehicle_id, type_id, url_private, description, name, code) VALUES(517, 1, 1, 1, '', '','Intersection Problems','INP');
INSERT INTO lesson ( lesson_id, status_id, vehicle_id, type_id, url_private, description, name, code) VALUES(518, 1, 1, 1, '', '','Intersection Solutions','INS');
INSERT INTO lesson ( lesson_id, status_id, vehicle_id, type_id, url_private, description, name, code) VALUES(519, 1, 1, 1, '', '','Inappropriate Speeds for Conditions','ISC');
INSERT INTO lesson ( lesson_id, status_id, vehicle_id, type_id, url_private, description, name, code) VALUES(520, 1, 1, 1, '', '','Maneuvering in Tight Spaces','MTS');
INSERT INTO lesson ( lesson_id, status_id, vehicle_id, type_id, url_private, description, name, code) VALUES(521, 1, 1, 1, '', '','Safe Driving at Night','NDR');
INSERT INTO lesson ( lesson_id, status_id, vehicle_id, type_id, url_private, description, name, code) VALUES(522, 1, 1, 1, '', '','Onboard Technology Distractions','OTD');
INSERT INTO lesson ( lesson_id, status_id, vehicle_id, type_id, url_private, description, name, code) VALUES(523, 1, 1, 1, '', '','Overtaking','OVR');
INSERT INTO lesson ( lesson_id, status_id, vehicle_id, type_id, url_private, description, name, code) VALUES(524, 1, 1, 1, '', '','Avoiding Collisions With Pedestrians and Cyclists','PAC');
INSERT INTO lesson ( lesson_id, status_id, vehicle_id, type_id, url_private, description, name, code) VALUES(525, 1, 1, 1, '', '','Eco Driving Trip Preparation','PRE');
INSERT INTO lesson ( lesson_id, status_id, vehicle_id, type_id, url_private, description, name, code) VALUES(526, 1, 1, 1, '', '','Road Rage','RAR');
INSERT INTO lesson ( lesson_id, status_id, vehicle_id, type_id, url_private, description, name, code) VALUES(527, 1, 1, 1, '', '','Avoiding Rear-End Collisions','REC');
INSERT INTO lesson ( lesson_id, status_id, vehicle_id, type_id, url_private, description, name, code) VALUES(528, 1, 1, 1, '', '','Roundabouts','RND');
INSERT INTO lesson ( lesson_id, status_id, vehicle_id, type_id, url_private, description, name, code) VALUES(529, 1, 1, 1, '', '','Safe Business Travel','SBT');
INSERT INTO lesson ( lesson_id, status_id, vehicle_id, type_id, url_private, description, name, code) VALUES(530, 1, 1, 1, '', '','Seatbelts and Airbags','SEA');
INSERT INTO lesson ( lesson_id, status_id, vehicle_id, type_id, url_private, description, name, code) VALUES(531, 1, 1, 1, '', '','SUVs, Trucks and Minivans','SUV');
INSERT INTO lesson ( lesson_id, status_id, vehicle_id, type_id, url_private, description, name, code) VALUES(532, 1, 1, 1, '', '','Underestimating Driving Risks','UDR');
INSERT INTO lesson ( lesson_id, status_id, vehicle_id, type_id, url_private, description, name, code) VALUES(533, 1, 1, 1, '', '','Vehicle Maintenance ','VHM');
INSERT INTO lesson ( lesson_id, status_id, vehicle_id, type_id, url_private, description, name, code) VALUES(534, 1, 1, 1, '', '','Avoiding the Worst Collisions at Intersections','WCI');

-- DELETE FROM course_lesson WHERE lesson_id>500
-- SELECT * FROM course_lesson cl;
INSERT INTO course_lesson(course_lesson_id, course_id, lesson_id, _order) values(501,25,501,13);
INSERT INTO course_lesson(course_lesson_id, course_id, lesson_id, _order) values(502,25,502,14);
INSERT INTO course_lesson(course_lesson_id, course_id, lesson_id, _order) values(503,25,503,15);
INSERT INTO course_lesson(course_lesson_id, course_id, lesson_id, _order) values(504,25,504,16);
INSERT INTO course_lesson(course_lesson_id, course_id, lesson_id, _order) values(505,25,505,17);
INSERT INTO course_lesson(course_lesson_id, course_id, lesson_id, _order) values(506,25,506,18);
INSERT INTO course_lesson(course_lesson_id, course_id, lesson_id, _order) values(507,25,507,19);
INSERT INTO course_lesson(course_lesson_id, course_id, lesson_id, _order) values(508,25,508,20);
INSERT INTO course_lesson(course_lesson_id, course_id, lesson_id, _order) values(509,25,509,21);
INSERT INTO course_lesson(course_lesson_id, course_id, lesson_id, _order) values(510,25,510,22);
INSERT INTO course_lesson(course_lesson_id, course_id, lesson_id, _order) values(511,25,511,23);
INSERT INTO course_lesson(course_lesson_id, course_id, lesson_id, _order) values(512,25,512,24);
INSERT INTO course_lesson(course_lesson_id, course_id, lesson_id, _order) values(513,25,513,25);
INSERT INTO course_lesson(course_lesson_id, course_id, lesson_id, _order) values(514,25,514,26);
INSERT INTO course_lesson(course_lesson_id, course_id, lesson_id, _order) values(515,25,515,27);
INSERT INTO course_lesson(course_lesson_id, course_id, lesson_id, _order) values(516,25,516,28);
INSERT INTO course_lesson(course_lesson_id, course_id, lesson_id, _order) values(517,25,517,29);
INSERT INTO course_lesson(course_lesson_id, course_id, lesson_id, _order) values(518,25,518,30);
INSERT INTO course_lesson(course_lesson_id, course_id, lesson_id, _order) values(519,25,519,31);
INSERT INTO course_lesson(course_lesson_id, course_id, lesson_id, _order) values(520,25,520,32);
INSERT INTO course_lesson(course_lesson_id, course_id, lesson_id, _order) values(521,25,521,33);
INSERT INTO course_lesson(course_lesson_id, course_id, lesson_id, _order) values(522,25,522,34);
INSERT INTO course_lesson(course_lesson_id, course_id, lesson_id, _order) values(523,25,523,35);
INSERT INTO course_lesson(course_lesson_id, course_id, lesson_id, _order) values(524,25,524,36);
INSERT INTO course_lesson(course_lesson_id, course_id, lesson_id, _order) values(525,25,525,37);
INSERT INTO course_lesson(course_lesson_id, course_id, lesson_id, _order) values(526,25,526,38);
INSERT INTO course_lesson(course_lesson_id, course_id, lesson_id, _order) values(527,25,527,39);
INSERT INTO course_lesson(course_lesson_id, course_id, lesson_id, _order) values(528,25,528,40);
INSERT INTO course_lesson(course_lesson_id, course_id, lesson_id, _order) values(529,25,529,41);
INSERT INTO course_lesson(course_lesson_id, course_id, lesson_id, _order) values(530,25,530,42);
INSERT INTO course_lesson(course_lesson_id, course_id, lesson_id, _order) values(531,25,531,43);
INSERT INTO course_lesson(course_lesson_id, course_id, lesson_id, _order) values(532,25,532,44);
INSERT INTO course_lesson(course_lesson_id, course_id, lesson_id, _order) values(533,25,533,45);
INSERT INTO course_lesson(course_lesson_id, course_id, lesson_id, _order) values(534,25,534,46);