-- 
-- Script was generated by Devart dbForge Studio for MySQL, Version 8.0.80.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/studio
-- Script date 24/08/2018 10:17:04 AM
-- Server version: 5.7.22
-- Run this script against dams_schema_int1 to synchronize it with dams_schema
-- 

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

SET NAMES 'utf8';

--
-- Set default database
--
USE dams_schema_int1xxxxxxxxxxxxxxxxxxxxxxx;

--
-- Alter column `code` on table `vehicle`
--
ALTER TABLE vehicle 
  CHANGE COLUMN code code VARCHAR(10) DEFAULT NULL;

--
-- Drop index `PRIMARY` from table `status`
--
ALTER TABLE status 
   DROP PRIMARY KEY;

--
-- Alter column `status_id` on table `status`
--
ALTER TABLE status 
  CHANGE COLUMN status_id status_id TINYINT(3) NOT NULL;

--
-- Alter column `status_id` on table `status`
--
ALTER TABLE status 
  MODIFY status_id TINYINT(3) NOT NULL AUTO_INCREMENT,
  ADD PRIMARY KEY (status_id);

--
-- Alter column `status` on table `lesson_version`
--
ALTER TABLE lesson_version 
  CHANGE COLUMN status status TINYINT(3) NOT NULL;

--
-- Create foreign key
--
ALTER TABLE lesson_version 
  ADD CONSTRAINT FK_lesson_version_status FOREIGN KEY (status)
    REFERENCES status(status_id);

--
-- Create foreign key
--
ALTER TABLE lesson 
  ADD CONSTRAINT FK_lesson_status_id FOREIGN KEY (status_id)
    REFERENCES status(status_id);

--
-- Create foreign key
--
ALTER TABLE lesson 
  ADD CONSTRAINT FK_lesson_vehicle_id FOREIGN KEY (vehicle_id)
    REFERENCES vehicle(vehicle_id);

--
-- Create index `task_id` on table `lesson_task`
--
ALTER TABLE lesson_task 
  ADD INDEX task_id(task_id);

--
-- Create foreign key
--
ALTER TABLE course 
  ADD CONSTRAINT FK_course_status_id FOREIGN KEY (status_id)
    REFERENCES status(status_id);

--
-- Drop column `item_id` from table `translation`
--
ALTER TABLE translation 
  DROP COLUMN item_id;

--
-- Drop column `parent_type_id` from table `translation`
--
ALTER TABLE translation 
  DROP COLUMN parent_type_id;

--
-- Drop column `parent_id` from table `translation`
--
ALTER TABLE translation 
  DROP COLUMN parent_id;

--
-- Drop column `version_id` from table `translation`
--
ALTER TABLE translation 
  DROP COLUMN version_id;

--
-- Change columns order on table `translation`
--
ALTER TABLE translation 
 MODIFY content_id INT(11) DEFAULT NULL AFTER type_id;

--
-- Create index `country_code` on table `translation`
--
ALTER TABLE translation 
  ADD INDEX country_code(country_code, language_code);

--
-- Create column `is_global` on table `dictionary`
--
ALTER TABLE dictionary 
  ADD COLUMN is_global TINYINT(1) DEFAULT NULL;

--
-- Drop index `ta_type_id_idx` from table `task`
--
ALTER TABLE task 
   DROP INDEX ta_type_id_idx;

--
-- Drop index `ta_status_id_idx` from table `task`
--
ALTER TABLE task 
   DROP INDEX ta_status_id_idx;

--
-- Alter column `type_id` on table `task`
--
ALTER TABLE task 
  CHANGE COLUMN type_id type_id INT(5) NOT NULL;

--
-- Alter column `status_id` on table `task`
--
ALTER TABLE task 
  CHANGE COLUMN status_id status_id TINYINT(3) NOT NULL;

--
-- Alter column `display_main` on table `task`
--
ALTER TABLE task 
  CHANGE COLUMN display_main display_main TINYINT(1) DEFAULT NULL;

--
-- Alter column `display_next` on table `task`
--
ALTER TABLE task 
  CHANGE COLUMN display_next display_next TINYINT(1) DEFAULT NULL;

--
-- Alter column `display_innav` on table `task`
--
ALTER TABLE task 
  CHANGE COLUMN display_innav display_innav TINYINT(1) DEFAULT 1;

--
-- Create index `ta_type_id_idx` on table `task`
--
ALTER TABLE task 
  ADD INDEX ta_type_id_idx(type_id);

--
-- Create index `ta_status_id_idx` on table `task`
--
ALTER TABLE task 
  ADD INDEX ta_status_id_idx(status_id);

--
-- Create foreign key
--
ALTER TABLE task 
  ADD CONSTRAINT FK_task_status_id FOREIGN KEY (status_id)
    REFERENCES status(status_id);

--
-- Create foreign key
--
ALTER TABLE task 
  ADD CONSTRAINT FK_task_type_id FOREIGN KEY (type_id)
    REFERENCES task_type(type_id);

--
-- Drop index `content_id_UNIQUE` from table `task_content`
--
ALTER TABLE task_content 
   DROP INDEX content_id_UNIQUE;

--
-- Drop column `content_id` from table `task_content`
--
ALTER TABLE task_content 
  DROP COLUMN content_id;

--
-- Alter column `value` on table `task_content`
--
ALTER TABLE task_content 
  CHANGE COLUMN value value TEXT DEFAULT NULL;

--
-- Create index `UK_task_content` on table `task_content`
--
ALTER TABLE task_content 
  ADD UNIQUE INDEX UK_task_content(task_group_id, attr_id, version_id);


ALTER TABLE task_dictionary 
  CHANGE COLUMN content_id content_id1 VARCHAR(10) DEFAULT NULL;







--
-- Create index `code` on table `country`
--

ALTER TABLE country 
  DROP INDEX code;  
ALTER TABLE country 
  DROP INDEX code_2;
ALTER TABLE country 
  ADD INDEX code(code);


--
-- Create index `code` on table `language`
--
ALTER TABLE language 
  DROP INDEX code;
ALTER TABLE language 
  DROP INDEX code_2;
ALTER TABLE language 
  ADD INDEX code(code);



--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;


ALTER TABLE lesson 
  CHANGE COLUMN name name VARCHAR(100) DEFAULT NULL;
